name: Build and Push Container Images

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - master

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Set up ko
        uses: ko-build/setup-ko@v0.7

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/cert-manager-sync
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push multi-arch images
        if: github.event_name != 'pull_request'
        env:
          KO_DOCKER_REPO: ${{ env.REGISTRY }}/${{ github.repository_owner }}/cert-manager-sync
        run: |
          # Build and push with ko - it will automatically tag based on git ref
          IMAGE_REF=$(ko build --bare --platform=all ./cmd/cert-manager-sync)
          echo "Built image: $IMAGE_REF"
          
          # If this is main/master branch, also tag as latest
          if [[ "${{ github.ref }}" == "refs/heads/main" ]] || [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "Creating latest tag..."
            REPO_BASE="${{ env.REGISTRY }}/${{ github.repository_owner }}/cert-manager-sync"
            docker buildx imagetools create --tag "${REPO_BASE}:latest" "$IMAGE_REF"
          fi

      - name: Build image for PR (dry-run)
        if: github.event_name == 'pull_request'
        env:
          KO_DOCKER_REPO: ko.local
        run: |
          # For PRs, test multiarch build locally without pushing
          ko build --platform=linux/amd64,linux/arm64,linux/arm/v7,linux/386,linux/ppc64le,linux/s390x --local ./cmd/cert-manager-sync
