name: Build and Push Container Images

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Set up ko
        uses: ko-build/setup-ko@v0.7

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push multi-arch images
        if: github.event_name != 'pull_request'
        env:
          KO_DOCKER_REPO: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        run: |
          # Convert tags to comma-separated list for ko
          TAGS=$(echo "${{ steps.meta.outputs.tags }}" | tr '\n' ',' | sed 's/,$//')
          echo "Building for tags: $TAGS"
          
          # Build and push multi-arch images with ko
          ko build --bare --platform=linux/amd64,linux/arm64 --tags="$TAGS" ./cmd/cert-manager-sync

      - name: Build image for PR (dry-run)
        if: github.event_name == 'pull_request'
        env:
          KO_DOCKER_REPO: ko.local
        run: |
          # For PRs, build locally without pushing (amd64 only for speed)
          ko build --platform=linux/amd64 --local ./cmd/cert-manager-sync
